[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "blue-pill"
version = "0.1.0"

[dependencies.stm32f103xx-hal]
path = "stm32f103xx-hal"
version = "0.1.0"

[dev-dependencies]
nb = "0.1.1"
cortex-m = "0.4.2"
mpu9250 = { git = "https://github.com/japaric/mpu9250" }
cortex-m-semihosting = "0.2.0"

[dev-dependencies.cortex-m-rt]
features = ["abort-on-panic"]
version = "0.3.12"

[dev-dependencies.stm32f103xx-hal]
features = ["rt"]
path = "stm32f103xx-hal"
version = "0.1.0"

[features]
rt = ["stm32f103xx-hal/rt"]

[profile.dev]
incremental = false
codegen-units = 1

[profile.release]
debug = true
lto = true

[workspace]
